-- CPG Brand Product Launch Demo - Infrastructure Setup
-- Creates warehouse, database, schemas, stages, compute pool, network rule, EAI

-- 1. Warehouse
CREATE WAREHOUSE IF NOT EXISTS AICOLLEGE
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = FALSE;

USE WAREHOUSE AICOLLEGE;

-- 2. Database and Schemas
CREATE DATABASE IF NOT EXISTS SKU_LAUNCH;

CREATE SCHEMA IF NOT EXISTS SKU_LAUNCH.INVENTORY;
CREATE SCHEMA IF NOT EXISTS SKU_LAUNCH.SKU_SALES;
CREATE SCHEMA IF NOT EXISTS SKU_LAUNCH.DISTRIBUTION;
CREATE SCHEMA IF NOT EXISTS SKU_LAUNCH.CONSUMER_INSIGHTS;

-- 3. Internal Stages (SSE encryption for AI_TRANSCRIBE compatibility)
CREATE STAGE IF NOT EXISTS SKU_LAUNCH.INVENTORY.RAW_FILES
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = (ENABLE = TRUE);

CREATE STAGE IF NOT EXISTS SKU_LAUNCH.SKU_SALES.RAW_FILES
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = (ENABLE = TRUE);

CREATE STAGE IF NOT EXISTS SKU_LAUNCH.DISTRIBUTION.RAW_FILES
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = (ENABLE = TRUE);

CREATE STAGE IF NOT EXISTS SKU_LAUNCH.CONSUMER_INSIGHTS.RAW_FILES
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = (ENABLE = TRUE);

CREATE STAGE IF NOT EXISTS SKU_LAUNCH.CONSUMER_INSIGHTS.RAW_AUDIO
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = (ENABLE = TRUE);

CREATE STAGE IF NOT EXISTS SKU_LAUNCH.INVENTORY.APP_SPECS
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- 4. Compute Pool for SPCS
CREATE COMPUTE POOL IF NOT EXISTS SKU_LAUNCH_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS
  AUTO_SUSPEND_SECS = 3600
  AUTO_RESUME = TRUE;

-- 5. Image Repository
CREATE IMAGE REPOSITORY IF NOT EXISTS SKU_LAUNCH.INVENTORY.IMAGE_REPO;

-- 6. Network Rule (update account host for your account)
CREATE OR REPLACE NETWORK RULE SKU_LAUNCH.INVENTORY.SKU_LAUNCH_EGRESS_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('sfsenorthamerica-rraz-aws1.snowflakecomputing.com:443');

-- 7. External Access Integration
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION SKU_LAUNCH_EAI
  ALLOWED_NETWORK_RULES = (SKU_LAUNCH.INVENTORY.SKU_LAUNCH_EGRESS_RULE)
  ENABLED = TRUE;
