-- CPG Brand Product Launch Demo - Load Data
-- Loads CSV data from the git repository stage into tables
-- Assumes git repo is at: @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/
-- Also loads MP3 audio files to the RAW_AUDIO stage

USE DATABASE SKU_LAUNCH;
USE WAREHOUSE AICOLLEGE;

----------------------------------------------------------------------
-- INVENTORY
----------------------------------------------------------------------
USE SCHEMA INVENTORY;

COPY INTO DIM_DISTRIBUTION_CENTERS (DC_ID, DC_NAME, CITY, STATE, LATITUDE, LONGITUDE, CAPACITY_UNITS)
FROM (SELECT $1, $2, $3, $4, $5, $6, $9
      FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/inventory/dim_distribution_centers.csv)
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');

COPY INTO DIM_SKU
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/inventory/dim_sku.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW_OF_DC_INVENTORY
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/inventory/raw_of_dc_inventory.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

----------------------------------------------------------------------
-- SKU_SALES
----------------------------------------------------------------------
USE SCHEMA SKU_SALES;

COPY INTO DIM_SKU
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/sku_sales/dim_sku.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO DIM_STORES (STORE_ID, RETAILER, REGION, STATE, CITY, LATITUDE, LONGITUDE)
FROM (SELECT $1, $2, $3, $4, $5, $6, $7
      FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/sku_sales/dim_stores.csv)
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');

COPY INTO RAW_OF_DAILY_STORE_POS
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/sku_sales/raw_of_daily_store_pos/
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW_OF_WEEKLY_SYNDICATED_POS
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/sku_sales/raw_of_weekly_syndicated_pos.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW_OF_PROMO_EVENTS
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/sku_sales/raw_of_promo_events.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO CONSUMER_PURCHASE
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/sku_sales/consumer_purchase.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO CONSUMER_FORECAST
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/sku_sales/consumer_forecast.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO PRELAUNCH_FORECAST
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/sku_sales/prelaunch_forecast.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO ML_SKU_FORECAST
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/sku_sales/ml_sku_forecast.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

----------------------------------------------------------------------
-- DISTRIBUTION
----------------------------------------------------------------------
USE SCHEMA DISTRIBUTION;

COPY INTO DIM_DISTRIBUTION_CENTERS (DC_ID, DC_NAME, CITY, STATE, LATITUDE, LONGITUDE, CAPACITY_UNITS)
FROM (SELECT $1, $2, $3, $4, $5, $6, $9
      FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/distribution/dim_distribution_centers.csv)
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');

COPY INTO DIM_MANUFACTURING_PLANTS
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/distribution/dim_manufacturing_plants.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO DIM_SKU
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/distribution/dim_sku.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO DIM_STORES (STORE_ID, RETAILER, REGION, STATE, CITY, LATITUDE, LONGITUDE)
FROM (SELECT $1, $2, $3, $4, $5, $6, $7
      FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/distribution/dim_stores.csv)
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');

COPY INTO RAW_OF_DC_SHIPMENTS
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/distribution/raw_of_dc_shipments.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

----------------------------------------------------------------------
-- CONSUMER_INSIGHTS
----------------------------------------------------------------------
USE SCHEMA CONSUMER_INSIGHTS;

COPY INTO RAW_OF_CALL_TRANSCRIPTS
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/consumer_insights/raw_of_call_transcripts.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW_OF_SOCIAL_MEDIA_FEEDBACK
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/data/consumer_insights/raw_of_social_media_feedback.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- Copy MP3 audio files from git stage to the RAW_AUDIO stage
COPY FILES INTO @SKU_LAUNCH.CONSUMER_INSIGHTS.RAW_AUDIO/calls/
FROM @SKU_LAUNCH.INVENTORY.SKU_LAUNCH_GIT/branches/main/audio/calls/;

-- Refresh audio stage directory for DIRECTORY() queries
ALTER STAGE RAW_AUDIO REFRESH;
