-- Colgate v2 Product Launch Demo - Load Data
-- Upload CSV files from data/ directory to stages, then COPY INTO tables
-- Run this AFTER uploading files to stages:
--   PUT file://data/inventory/*.csv @SKU_LAUNCH.INVENTORY.RAW_FILES/seed/
--   PUT file://data/sku_sales/*.csv @SKU_LAUNCH.SKU_SALES.RAW_FILES/seed/
--   PUT file://data/distribution/*.csv @SKU_LAUNCH.DISTRIBUTION.RAW_FILES/seed/
--   PUT file://data/consumer_insights/*.csv @SKU_LAUNCH.CONSUMER_INSIGHTS.RAW_FILES/seed/
--   PUT file://audio/calls/*.mp3 @SKU_LAUNCH.CONSUMER_INSIGHTS.RAW_AUDIO/calls/

USE DATABASE SKU_LAUNCH;

----------------------------------------------------------------------
-- INVENTORY
----------------------------------------------------------------------
USE SCHEMA INVENTORY;

COPY INTO DIM_DISTRIBUTION_CENTERS
FROM @RAW_FILES/seed/dim_distribution_centers.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO DIM_SKU
FROM @RAW_FILES/seed/dim_sku.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW_OF_DC_INVENTORY
FROM @RAW_FILES/seed/raw_of_dc_inventory.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

----------------------------------------------------------------------
-- SKU_SALES
----------------------------------------------------------------------
USE SCHEMA SKU_SALES;

COPY INTO DIM_SKU
FROM @RAW_FILES/seed/dim_sku.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO DIM_STORES
FROM @RAW_FILES/seed/dim_stores.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW_OF_DAILY_STORE_POS
FROM @RAW_FILES/seed/raw_of_daily_store_pos/
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW_OF_WEEKLY_SYNDICATED_POS
FROM @RAW_FILES/seed/raw_of_weekly_syndicated_pos.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW_OF_PROMO_EVENTS
FROM @RAW_FILES/seed/raw_of_promo_events.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO CONSUMER_PURCHASE
FROM @RAW_FILES/seed/consumer_purchase.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO CONSUMER_FORECAST
FROM @RAW_FILES/seed/consumer_forecast.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO PRELAUNCH_FORECAST
FROM @RAW_FILES/seed/prelaunch_forecast.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO ML_SKU_FORECAST
FROM @RAW_FILES/seed/ml_sku_forecast.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

----------------------------------------------------------------------
-- DISTRIBUTION
----------------------------------------------------------------------
USE SCHEMA DISTRIBUTION;

COPY INTO DIM_DISTRIBUTION_CENTERS
FROM @RAW_FILES/seed/dim_distribution_centers.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO DIM_MANUFACTURING_PLANTS
FROM @RAW_FILES/seed/dim_manufacturing_plants.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO DIM_SKU
FROM @RAW_FILES/seed/dim_sku.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO DIM_STORES
FROM @RAW_FILES/seed/dim_stores.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW_OF_DC_SHIPMENTS
FROM @RAW_FILES/seed/raw_of_dc_shipments.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

----------------------------------------------------------------------
-- CONSUMER_INSIGHTS
----------------------------------------------------------------------
USE SCHEMA CONSUMER_INSIGHTS;

COPY INTO RAW_OF_CALL_TRANSCRIPTS
FROM @RAW_FILES/seed/raw_of_call_transcripts.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW_OF_SOCIAL_MEDIA_FEEDBACK
FROM @RAW_FILES/seed/raw_of_social_media_feedback.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- Refresh audio stage directory
ALTER STAGE RAW_AUDIO REFRESH;
