-- CPG Brand Product Launch Demo - Views

USE DATABASE SKU_LAUNCH;
USE SCHEMA DISTRIBUTION;

create or replace view V_DC_BACKUP_OPTIONS(
	PRIMARY_DC_ID,
	PRIMARY_DC_NAME,
	PRIMARY_REGIONS,
	BACKUP_DC_ID,
	BACKUP_DC_NAME,
	BACKUP_REGIONS,
	DISTANCE_MILES,
	BACKUP_RANK
) as
WITH dc_distances AS (
  SELECT dc1.DC_ID as PRIMARY_DC_ID, dc1.DC_NAME as PRIMARY_DC_NAME, dc1.REGIONS_SERVED as PRIMARY_REGIONS,
    dc2.DC_ID as BACKUP_DC_ID, dc2.DC_NAME as BACKUP_DC_NAME, dc2.REGIONS_SERVED as BACKUP_REGIONS,
    ROUND(ST_DISTANCE(dc1.LOCATION, dc2.LOCATION) / 1609.34, 0) as DISTANCE_MILES,
    ROW_NUMBER() OVER (PARTITION BY dc1.DC_ID ORDER BY ST_DISTANCE(dc1.LOCATION, dc2.LOCATION)) as BACKUP_RANK
  FROM SKU_LAUNCH.DISTRIBUTION.DIM_DISTRIBUTION_CENTERS dc1
  CROSS JOIN SKU_LAUNCH.DISTRIBUTION.DIM_DISTRIBUTION_CENTERS dc2
  WHERE dc1.DC_ID != dc2.DC_ID
)
SELECT * FROM dc_distances WHERE BACKUP_RANK <= 3;
