-- CPG Brand Product Launch Demo - Cleanup
-- Drops all objects created by this demo

USE ROLE ACCOUNTADMIN;

-- SPCS Service
DROP SERVICE IF EXISTS SKU_LAUNCH.INVENTORY.SKU_LAUNCH_DASHBOARD;

-- Compute Pool
DROP COMPUTE POOL IF EXISTS SKU_LAUNCH_POOL;

-- External Access Integration
DROP EXTERNAL ACCESS INTEGRATION IF EXISTS SKU_LAUNCH_EAI;

-- Agent (if DDL-created)
DROP AGENT IF EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS.PRODUCT_LAUNCH_AGENT;

-- Database (removes all schemas, tables, DTs, views, stages, search services, semantic views)
DROP DATABASE IF EXISTS SKU_LAUNCH;

-- Warehouse
DROP WAREHOUSE IF EXISTS SKU_LAUNCH_WH;

-- Git Integration
DROP INTEGRATION IF EXISTS SKU_LAUNCH_GIT_INTEGRATION;

-- Role
DROP ROLE IF EXISTS SKU_LAUNCH_ROLE;
